Create zh_TW.lang
TeamTotemic/Totemic pull request #46
Opened 2017-04-02 12:58 UTC by NatsuArashi

Traditional Chinese support.

2017-04-02 17:32 UTC, ljfa-ag requested changes
Why did you leave some things untranslated?

2017-04-03 13:08 UTC, NatsuArashi commented
Working...
Now finished.

2017-04-03 17:32 UTC, ljfa-ag approved these changes

2017-04-03 17:32 UTC, merged

2017-04-03 17:32 UTC, ljfa-ag commented
Alright, thanks!